### ISSUE TITLE
Prettier wraps long line

### ISSUE THREAD

**Issue by hoest** [shannonmoeller/stylelint-config-prettier#13]
I'm using `stylinelint` in SublimeText with `stylelint-config-standard` and `stylelint-config-prettier`. I have this issue:

![image](https://user-images.githubusercontent.com/606546/37585570-dae36554-2b59-11e8-873c-3c277aa0839a.png)

Prettier wraps the long line, but Stylelint does not like this... What can I do to fix this?

**Comment by shannonmoeller** [comment]
May I see your stylelint config? We're specifically disabling the `indentation` rule, so something seems fishy.

**Comment by hoest** [comment]
This is my `.stylelintrc.yml`:

```yml
---
extends:
- stylelint-config-standard
- stylelint-config-prettier

rules:
  indentation: 2
  function-url-quotes: always
  property-no-vendor-prefix: true
  value-no-vendor-prefix: true
```
