### ISSUE TITLE
at-rule-empty-line-before conflicts with prettier and is part of stylelint-config-standard

### ISSUE THREAD

**Issue by felixfbecker** [shannonmoeller/stylelint-config-prettier#4]
Prettier:
```scss
    .navbar-toggler {
      @if (lightness( $navbar-brand-bg ) > 40) {
        color: $navbar-color;
      } @else {
        color: white;
      }
    }
```

After `stylelint --fix`:
```scss
    .navbar-toggler {
      @if (lightness( $navbar-brand-bg ) > 40) {
        color: $navbar-color;
      }

 @else {
        color: white;
      }
    }
```
